#!/usr/bin/env python3
"""One GitHub-native Solitude register study; leave the active README untouched."""
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.sax.saxutils import escape

from build_folio import ROOT, FOLIO, checksum, popular_works, theme_url
from render_previews import render_markdown, source_hash

STUDY = FOLIO / 'studies/register'
MANIFEST = ROOT / '.review/register-manifest.json'
MODES = ('dark', 'light')
SOURCES = [
    'https://x.com/_zuji/status/2099779205135511967',
    'https://x.com/bedirhandogn/status/2098336712812335257',
    'https://x.com/slavakornilov/status/2096724597080989846',
]


def register_svg(mode, colors, badge):
    """A restrained folder silhouette, an untouched desktop and exact ANSI swatches."""
    body, edge, _, _, _, _, _, tab = colors
    shadow = '0.58' if mode == 'dark' else '0.23'
    front = 'M24 68V38Q24 24 38 24H227Q235 24 241 30L273 62H584L600 78V456L584 472H24Z'
    rear = 'M36 60V24Q36 12 48 12H282L314 44H590L608 62V448L590 466H36Z'
    tab_path = 'M24 68V38Q24 24 38 24H227Q235 24 241 30L273 62H584L600 78H24Z'
    swatches = ''.join(f'<rect x="{44 + i * 22}" y="420" width="22" height="30" fill="{color}" />'
                       for i, color in enumerate(colors))
    scale = 624 / 248
    badge_w = (badge['width'] + 24) * scale
    # The actual 60 x 20 badge remains the same displayed size, including its shadow.
    return f'''<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1248" height="984" viewBox="0 0 624 492">
  <title>Solitude — theme register study</title>
  <desc>Full original desktop, exact ANSI colors 0 through 7, and {badge['stars']} GitHub stars from the dated snapshot. Static linked image, not an interactive tab interface.</desc>
  <defs>
    <filter id="float" x="-10%" y="-10%" width="120%" height="125%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="4" /><feOffset dy="6" /></filter>
    <linearGradient id="edge" x1="0" y1="0" x2="0.8" y2="1"><stop stop-color="{tab}" stop-opacity="0.7" /><stop offset="0.6" stop-color="{edge}" stop-opacity="0.4" /><stop offset="1" stop-color="{edge}" stop-opacity="0.2" /></linearGradient>
  </defs>
  <path d="{front}" fill="#000000" opacity="{shadow}" filter="url(#float)" />
  <path d="{rear}" fill="{edge}" stroke="{colors[4]}" stroke-width="1" />
  <path d="{front}" fill="{body}" />
  <path d="{tab_path}" fill="{tab}" />
  <path d="{front}" fill="none" stroke="url(#edge)" stroke-width="1.5" />
  <text x="44" y="60" fill="{body}" font-family="IBM Plex Sans" font-size="38" font-weight="500">Solitude</text>
  <image x="32" y="84" width="560" height="315" xlink:href="sources/popular-solitude.png" />
  <g id="ansi-palette"><title>ANSI color00–07, left to right</title>{swatches}<rect x="44" y="420" width="176" height="30" fill="none" stroke="{edge}" stroke-width="1" /></g>
  <image x="{580 - badge_w + 12 * scale}" y="400" width="{badge_w}" height="{36 * scale}" xlink:href="assets/badge-solitude-{mode}.png" />
</svg>'''


def picture(new, width, snapshot):
    base = './assets/solitude' if new else '../../assets/popular-solitude'
    kind = 'Register study' if new else 'Previous presentation'
    stamp = snapshot['fetched_at'][:10]
    stars = snapshot['badges']['solitude']['stars']
    palette = '; exact ANSI colors 00–07, left to right' if new else ''
    return f'<a href="{theme_url("solitude")}"><picture><source media="(prefers-color-scheme: dark)" srcset="{base}-dark.png" /><img src="{base}-light.png" alt="Solitude — {kind}; full desktop preview{palette}; {stars} GitHub stars, checked {stamp}" title="Star snapshot · {stamp}" width="{width}" height="{width * 196 // 248}" /></picture></a>'


def render_page(markdown, output, label, standalone=False):
    # Both views use real GitHub-rendered README markup and the existing local frame.
    resolved = markdown.replace('"../../assets/', '"./folio/assets/').replace('"./assets/', '"./folio/studies/register/assets/')
    resolved = resolved.replace('"../../collection/', '"./folio/collection/').replace('"../../THEMES.md"', '"./collection.html?view=readme"')
    rendered, renderer = render_markdown(resolved)
    page = (ROOT / 'folio.html').read_text()
    page = page.replace('Generated by scripts/render_folio.py.', 'Generated by scripts/build_register_study.py.')
    page, count = re.subn(r'(<article class="markdown-body"[^>]*>).*?(</article>)',
                          lambda m: m[1] + '\n' + rendered + '\n' + m[2], page, count=1, flags=re.S)
    assert count == 1
    page = re.sub(r'(<meta name="profile-source-sha256" content=")[^"]+',
                  lambda m: m[1] + source_hash(markdown), page)
    page = page.replace('<title>HANCORE · Compact GitHub profile</title>', f'<title>HANCORE · {label}</title>')
    page = page.replace('HANCORE-linux / README.md', f'HANCORE-linux / {label}')
    links = [('folio.html', 'Profil'), ('collection.html?view=readme', 'Alle Themes'), ('identity.html', 'Namensstudie'), ('register.html', 'Registerstudie'), ('register-profile.html', 'Im Profil')]
    nav = '<nav class="preview-tabs" aria-label="Study comparison">' + ''.join(
        f'<a href="./{route}"' + (' aria-current="page"' if route == output else '') + f'>{name}</a>'
        for route, name in links) + '</nav>'
    page = re.sub(r'<nav class="preview-tabs".*?</nav>', lambda _: nav, page, count=1, flags=re.S)
    if standalone:
        page = re.sub(r'<label for="preview-wordmark">.*?</select>', '', page, count=1, flags=re.S)
        page = re.sub(r'<section class="folio-pins".*?</section>', '', page, count=1, flags=re.S)
        page = page.replace('GitHub-gerendertes README. Profilrahmen angenähert, Pins als lokaler Vorschlag.',
                            'GitHub-gerenderte Registerstudie. Profilrahmen angenähert.')
    target = ROOT / output
    target.write_text(page)
    return target, renderer


def validate_assets():
    colors = json.loads((FOLIO / 'palettes.json').read_text())['themes']['solitude']['colors']
    ns = {'svg': 'http://www.w3.org/2000/svg'}
    for mode in MODES:
        svg = ET.parse(FOLIO / f'register-solitude-{mode}.svg').getroot()
        swatches = svg.findall('.//svg:g[@id="ansi-palette"]/svg:rect', ns)[:8]
        assert [rect.get('fill') for rect in swatches] == colors
        assert all(rect.get('width') == '22' and rect.get('height') == '30' for rect in swatches)
        shot = svg.find('svg:image', ns)
        assert shot.get('width') == '560' and shot.get('height') == '315'
        assert shot.get('{http://www.w3.org/1999/xlink}href') == 'sources/popular-solitude.png'
        assert 'filter' not in shot.attrib, 'Never blur the screenshot'
        assert svg.get('viewBox') == '0 0 624 492'
        data = (STUDY / f'assets/solitude-{mode}.png').read_bytes()
        assert data[:8] == b'\x89PNG\r\n\x1a\n'
        assert int.from_bytes(data[16:20], 'big') == 1248 and int.from_bytes(data[20:24], 'big') == 984
        assert len(data) < 1_500_000, 'Oversized README asset'
        # Pixel-level regression: a successfully exported but blank image must fail.
        spread = subprocess.check_output(['magick', str(STUDY / f'assets/solitude-{mode}.png'),
                                          '-crop', '1120x630+64+168', '+repage',
                                          '-format', '%[standard-deviation]', 'info:'], text=True)
        assert float(spread) > 1000, 'The original desktop did not render'
        badge_spread = subprocess.check_output(['magick', str(STUDY / f'assets/solitude-{mode}.png'),
                                                '-crop', '290x90+864+826', '+repage',
                                                '-format', '%[standard-deviation]', 'info:'], text=True)
        assert float(badge_spread) > 1000, 'The stars badge did not render'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--render', action='store_true', help='Render the two local GitHub previews')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    subprocess.run([sys.executable, str(ROOT / 'scripts/build_folio.py'), '--check'], check=True)
    if args.check:
        manifest = json.loads(MANIFEST.read_text())
        for section in ('inputs', 'outputs'):
            for name, digest in manifest[section].items():
                assert checksum(ROOT / name) == digest, f'Stale register {section}: {name}'
        assert all(renderer.startswith('GitHub Markdown') for renderer in manifest['renderers'])
        assert len(manifest['renderers']) == 1, 'Render the historical single-card study before handoff'
        validate_assets()
        print('OK register study: original desktop, exact 00–07 palette, 2 PNGs and fresh GitHub previews')
        return
    work = next(work for work in popular_works() if work['theme_slug'] == 'solitude')
    palette = json.loads((FOLIO / 'palettes.json').read_text())['themes']['solitude']
    assert checksum(FOLIO / 'sources/palettes/solitude.toml') == palette['sha256']
    snapshot = json.loads((FOLIO / 'badge-snapshot.json').read_text())
    (STUDY / 'assets').mkdir(parents=True, exist_ok=True)
    outputs = []
    with tempfile.TemporaryDirectory(prefix='hancore-register-fonts-') as temp:
        config = Path(temp) / 'fonts.conf'
        config.write_text(f'<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd"><fontconfig><dir>{escape(str(FOLIO / "type"))}</dir><cachedir>{escape(temp)}/cache</cachedir></fontconfig>')
        env = dict(os.environ, FONTCONFIG_FILE=str(config))
        match = subprocess.check_output(['fc-match', '-f', '%{family}', 'IBM Plex Sans'], env=env, text=True)
        assert 'IBM Plex Sans' in match.split(','), f'Font fallback: {match}'
        for mode in MODES:
            # librsvg only loads relative resources inside the SVG's base directory.
            # Keep native SVG sources beside the existing folio assets and screenshots.
            svg = FOLIO / f'register-solitude-{mode}.svg'
            png = STUDY / f'assets/solitude-{mode}.png'
            svg.write_text(register_svg(mode, palette['colors'], snapshot['badges']['solitude']))
            subprocess.run(['rsvg-convert', str(svg), '-o', str(png)], env=env, check=True)
            outputs.extend([svg, png])
    readme = STUDY / 'README.md'
    readme.write_text(f'''<p align="center"><sub>SOLITUDE / REGISTERSTUDIE</sub></p>

<p align="center">{picture(True, 496, snapshot)}</p>

<p align="center"><sub>Vergleich bei 248 px · bisher / Register</sub></p>

<p align="center">
  {picture(False, 248, snapshot)}
  {picture(True, 248, snapshot)}
</p>

<p align="center"><sub>Originaler Desktop · echte Farben 00–07 · bestehendes Stars-Badge<br />Ursprüngliche Einzelstudie. Die komplette Serie ist jetzt im Profil und im Theme-Archiv zu sehen.</sub></p>
''')
    # Keep the old context route useful: it now shows the approved complete series.
    profile = STUDY / 'profile.md'
    content = (FOLIO / 'README.md').read_text()
    content = content.replace('"./assets/', '"../../assets/').replace('"./collection/', '"../../collection/')
    content = content.replace('"./THEMES.md"', '"../../THEMES.md"')
    profile.write_text(content)
    outputs.extend([readme, profile])
    renderers = []
    if args.render:
        for source, output, label, standalone in [(readme, 'register.html', 'Solitude · Registerstudie', True)]:
            markdown = source.read_text().replace('"../../../THEMES.md"', '"./THEMES.md"')
            target, renderer = render_page(markdown, output, label, standalone)
            outputs.append(target)
            renderers.append(renderer)
    inputs = [Path(__file__).resolve(), FOLIO / 'README.md', ROOT / 'folio.html', FOLIO / 'preview.js', FOLIO / 'preview.css',
              ROOT / 'scripts/render_previews.py', FOLIO / 'palettes.json', FOLIO / 'popular-themes.json', FOLIO / 'badge-snapshot.json',
              FOLIO / 'sources/popular-solitude.png', FOLIO / 'sources/palettes/solitude.toml',
              FOLIO / 'type/plex-sans/IBMPlexSans.ttf', FOLIO / 'type/plex-sans/OFL.txt']
    inputs.extend(sorted((FOLIO / 'assets').glob('*.png')))
    manifest = {'description': 'One Solitude register study. No reference artwork copied; no generative imagery.',
                'references': SOURCES, 'desktop': work, 'font': 'IBM Plex Sans Medium; bundled SIL OFL font.',
                'renderers': renderers,
                'inputs': {str(p.relative_to(ROOT)): checksum(p) for p in inputs},
                'outputs': {str(p.relative_to(ROOT)): checksum(p) for p in outputs}}
    MANIFEST.write_text(json.dumps(manifest, indent=2) + '\n')
    validate_assets()
    print('OK exported original Solitude register study' + (' and GitHub-rendered comparison' if args.render else ' (preview render pending)'))


if __name__ == '__main__':
    main()
