#!/usr/bin/env python3
"""Build the theme archive and publication images from local, verified sources."""
from __future__ import annotations

import argparse
import base64
import hashlib
import html
import json
import re
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEGIN = '<!-- BEGIN GENERATED: themes -->'
END = '<!-- END GENERATED: themes -->'
SECTIONS = (
    ('shibumi', '01', 'SHIBUMI SHELL'),
    ('waybar', '02', 'WAYBAR THEMES'),
    ('rise', '03', 'QUICKSHELL RISE'),
    ('themes', '04', 'THEME STUDIES'),
    ('marketplace', '05', 'PLUGIN MARKETPLACE'),
    ('archive', 'A', 'THEME ARCHIVE'),
    ('credits', 'C', 'ACKNOWLEDGEMENTS'),
)


def section_svg(number: str, title: str) -> str:
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 108">
  <title>{html.escape(title)}</title>
  <rect width="900" height="108" fill="#0a0c0d"/>
  <path d="M24 20V88M876 20V88" stroke="#343736" fill="none"/>
  <path d="M24 20V88" stroke="#df6124" stroke-width="3"/>
  <text x="44" y="69" fill="#df6124" font-family="JetBrains Mono, monospace" font-size="32">{number}</text>
  <text x="116" y="74" fill="#ebe5d6" font-family="Nimbus Sans Narrow, Arial Narrow, sans-serif" font-size="56" font-weight="700">{html.escape(title)}</text>
  <path d="M831 53h25v7h-25z" fill="#df6124"/>
  <circle cx="876" cy="88" r="2" fill="#df6124"/>
</svg>
'''


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def repository(theme: dict) -> str:
    return f'https://github.com/HANCORE-linux/omarchy-{theme["slug"]}-theme'


def theme_picture(themes: list[dict]) -> str:
    names = html.escape(', '.join(t['name'] for t in themes))
    return f'''<a href="./THEMES.md">
  <picture>
    <source media="(max-width: 600px)" srcset="./assets/themes/selected-mobile.webp" />
    <img src="./assets/themes/selected.webp" alt="Real desktops in {names}, with a small selection of each theme's colors" width="1600" />
  </picture>
</a>'''


def theme_svg(themes: list[dict], mobile: bool) -> str:
    width, height = (640, 1416) if mobile else (1600, 432)
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 {width} {height}">',
             '<title>Selected themes — ' + html.escape(', '.join(t['name'] for t in themes)) + '</title>',
             f'<rect width="{width}" height="{height}" fill="#0a0c0d"/>']
    for i, theme in enumerate(themes):
        x, y, w = (24, 24 + i * 468, 592) if mobile else (24 + i * 528, 24, 496)
        image_h = w * 9 / 16
        parts += [f'<g transform="translate({x} {y})">',
                  f'<text x="0" y="39" fill="#ebe5d6" font-family="Nimbus Sans Narrow, sans-serif" font-weight="700" font-size="40">{html.escape(theme["name"])}</text>',
                  f'<image xlink:href="../sources/{theme["image"]}" x="0" y="64" width="{w}" height="{image_h}"/>']
        for j, color in enumerate(theme['palette']):
            swatch_w = w / len(theme['palette'])
            parts.append(f'<rect x="{j * swatch_w}" y="{76 + image_h}" width="{swatch_w}" height="12" fill="{color}"/>')
        parts.append('</g>')
    return '\n'.join(parts) + '\n</svg>\n'


def expected_documents(themes: list[dict], selected: list[dict]) -> dict[str, str]:
    count = len(themes)
    readme = (ROOT / 'README.md').read_text()
    if readme.count(BEGIN) != 1 or readme.count(END) != 1:
        raise ValueError('README needs exactly one generated theme region')
    links = ' · '.join(f'<a href="{repository(t)}">{html.escape(t["name"])}</a>' for t in selected)
    region = f'{BEGIN}\n{theme_picture(selected)}\n\n<p><sub>{links}</sub><br /><sub><a href="./THEMES.md">All {count} themes ↗</a></sub></p>\n{END}'
    readme = readme[:readme.index(BEGIN)] + region + readme[readme.index(END) + len(END):]
    archive = ['<!-- Generated by scripts/build_profile.py from data/themes.json. -->',
               '<h1><img src="./assets/brand/section-archive.webp" alt="Theme archive" width="900" height="108" /></h1>', '',
               f'<p><sub>{count} Omarchy themes. Different atmospheres, one desktop.</sub></p>', '',
               '[← Back to profile](./README.md) · [All themes](#all-themes)', '']
    for t in selected:
        archive += [f'## {t["name"]}', '',
                    f'<a href="{repository(t)}"><img src="./assets/themes/{t["slug"]}.webp" alt="{html.escape(t["name"])} desktop screenshot" width="1600" height="900" /></a>', '',
                    f'<p><sub>{html.escape(t["description"])}. <a href="{repository(t)}">Explore {html.escape(t["name"])} ↗</a></sub></p>', '']
    archive += ['## All themes', '', '| Theme | Character |', '| --- | --- |']
    archive += [f'| [{t["name"]}]({repository(t)}) | {t["description"]} |' for t in themes]
    archive += ['', '[← Back to profile](./README.md)', '']
    return {'README.md': readme, 'THEMES.md': '\n'.join(archive),
            'assets/themes/selected-source.svg': theme_svg(selected, False),
            'assets/themes/selected-mobile-source.svg': theme_svg(selected, True),
            **{f'assets/brand/section-{slug}-source.svg': section_svg(number, title) for slug, number, title in SECTIONS}}


def export_images(selected: list[dict]) -> list[str]:
    svg_exports = [('assets/brand/hero-source.svg', 'assets/brand/hero.webp'),
                   *[(f'assets/brand/section-{slug}-source.svg', f'assets/brand/section-{slug}.webp') for slug, _, _ in SECTIONS],
                   *[(f'assets/systems/{n}-source.svg', f'assets/systems/{n}.webp') for n in ('shibumi', 'waybar', 'rise')],
                   *[(f'assets/themes/{n}-source.svg', f'assets/themes/{n}.webp') for n in ('selected', 'selected-mobile')]]
    outputs = []
    with tempfile.TemporaryDirectory(prefix='hancore-profile-export-') as temp:
        for source, output in svg_exports:
            png = Path(temp) / 'render.png'
            source_path = ROOT / source
            # librsvg rejects sibling-directory image references. Embed verified
            # local inputs only for rendering; keep the editable SVG readable.
            def embed(match):
                path = (source_path.parent / match.group(1)).resolve()
                if not path.is_relative_to(ROOT / 'assets/sources'):
                    raise ValueError(f'Unexpected image reference: {path}')
                mime = 'image/png' if path.suffix == '.png' else 'image/webp'
                encoded = base64.b64encode(path.read_bytes()).decode()
                return f'xlink:href="data:{mime};base64,{encoded}"'
            standalone = re.sub(r'xlink:href="([^"]+)"', embed, source_path.read_text())
            svg = Path(temp) / 'render.svg'
            svg.write_text(standalone)
            subprocess.run(['rsvg-convert', str(svg), '-o', str(png)], check=True)
            subprocess.run(['magick', str(png), '-define', 'webp:lossless=true', str(ROOT / output)], check=True)
            outputs.append(output)
        for t in selected:
            output = f'assets/themes/{t["slug"]}.webp'
            subprocess.run(['magick', str(ROOT / 'assets/sources' / t['image']), '-resize', '1600x900',
                            '-define', 'webp:method=6', '-quality', '94', str(ROOT / output)], check=True)
            outputs.append(output)
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Check generated content and hashes without writing')
    args = parser.parse_args()
    themes = json.loads((ROOT / 'data/themes.json').read_text())
    assert [t['id'] for t in themes] == list(range(1, len(themes) + 1)), 'Theme IDs must be ordered and unique'
    assert len({t['slug'] for t in themes}) == len(themes), 'Duplicate theme slug'
    assert all(re.fullmatch(r'[a-z0-9-]+', t['slug']) for t in themes), 'Invalid theme slug'
    selected = sorted((t for t in themes if 'order' in t), key=lambda t: t['order'])
    assert len(selected) == 3 and [t['order'] for t in selected] == [0, 1, 2], 'Exactly three ordered selections required'
    for t in selected:
        assert all(re.fullmatch(r'#[0-9a-fA-F]{6}', c) for c in t['palette']), 'Invalid palette color'
    sources = json.loads((ROOT / 'data/sources.json').read_text())
    for source in sources:
        assert digest(ROOT / source['path']) == source['sha256'], f'Source changed: {source["path"]}'
    documents = expected_documents(themes, selected)
    if args.check:
        for name, expected in documents.items():
            assert (ROOT / name).read_text() == expected, f'Stale generated file: {name}'
        manifest = json.loads((ROOT / 'assets/provenance.json').read_text())
        for name, expected in {**manifest['inputs'], **manifest['outputs']}.items():
            assert digest(ROOT / name) == expected, f'Stale or changed asset: {name}'
        print(f'OK: {len(themes)} themes, {len(sources)} verified captures, generated documents and asset hashes')
        return
    for name, content in documents.items():
        (ROOT / name).write_text(content)
    outputs = export_images(selected)
    inputs = ['data/themes.json', 'data/sources.json', 'scripts/build_profile.py']
    inputs += [s['path'] for s in sources]
    inputs += [str(p.relative_to(ROOT)) for folder in ('assets/brand', 'assets/systems', 'assets/themes')
               for p in sorted((ROOT / folder).glob('*-source.svg'))]
    outputs += ['assets/brand/avatar-h.png', 'assets/brand/avatar-h-construct.png']
    manifest = {'version': 3, 'publication_status': 'local-review', 'build': 'python scripts/build_profile.py',
                'notes': ['Screenshots retain their original UI and colors; framing and crops are defined in SVG sources.',
                          'Rise uses a preserved V1 carousel capture, not a newly captured runtime or a V2 screenshot.',
                          'Theme screenshots may contain third-party wallpaper; original asset credits remain with their repositories.',
                          'The small palette samples are not complete ANSI palettes.'],
                'sources': sources, 'inputs': {p: digest(ROOT / p) for p in inputs},
                'outputs': {p: digest(ROOT / p) for p in outputs}}
    (ROOT / 'assets/provenance.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(f'Built {len(outputs)} images and the {len(themes)}-theme archive')


if __name__ == '__main__':
    main()
