"""Individually linked inspiration mounts in native, wrapping three-card rows."""
import hashlib
from html import escape
import json
from pathlib import Path

FOLIO = Path(__file__).resolve().parents[1] / 'folio'


def people():
    return json.loads((FOLIO / 'acknowledgements.json').read_text())['people']


def acknowledgement_svg(person, mode):
    avatar = json.loads((FOLIO / 'avatar-sources.json').read_text())['avatars'][person['slug']]
    assert avatar['github'].casefold() == person['github'].casefold()
    assert avatar['width'] == avatar['height']
    assert hashlib.sha256((FOLIO / avatar['path']).read_bytes()).hexdigest() == avatar['sha256']
    dark = mode == 'dark'
    paper, edge, ink, secondary = ('#191c1e', '#353a3d', '#e8e3d9', '#bfc4c9') if dark else ('#e9e7e0', '#c6c5bf', '#262522', '#50565b')
    outline = 'M24 16H600V174L578 196H24Z'
    return f'''<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1248" height="448" viewBox="0 0 624 224">
  <title>{escape(person['name'])} / {escape(person['role'])}; public GitHub avatar</title>
  <defs><filter id="float" x="-15%" y="-50%" width="130%" height="210%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="8" /><feOffset dy="10" /></filter></defs>
  <path d="{outline}" fill="#000000" opacity="{'0.48' if dark else '0.19'}" filter="url(#float)" />
  <path d="{outline}" fill="{paper}" stroke="{edge}" stroke-width="1.5" />
  <image x="36" y="42" width="128" height="128" xlink:href="{escape(avatar['path'], quote=True)}" />
  <text x="392" y="96" text-anchor="middle" fill="{ink}" font-family="IBM Plex Sans" font-size="46" font-weight="600">{escape(person['name'])}</text>
  <text x="392" y="150" text-anchor="middle" fill="{secondary}" font-family="IBM Plex Sans" font-size="40" font-weight="500">{escape(person['role'])}</text>
</svg>'''


def acknowledgement_markdown():
    from folio_labels import label_picture
    cards = []
    for person in people():
        slug = person['slug']
        alt = escape(f'{person["name"]} / {person["role"]}', quote=True)
        cards.append(f'<a href="{escape(person["url"], quote=True)}"><picture>'
                     f'<source media="(prefers-color-scheme: dark)" srcset="./assets/thanks-{slug}-dark.png" />'
                     f'<img src="./assets/thanks-{slug}-light.png" width="248" height="89" alt="{alt}" />'
                     '</picture></a>')
    rows = ['<p align="center">' + ''.join(cards[start:start + 3]) + '</p>'
            for start in range(0, len(cards), 3)]
    return ('<!-- Generated by scripts/build_folio.py. Up to three inspiration cards per row. -->\n'
            '<p><a href="https://github.com/HANCORE-linux">← Back to profile</a></p>\n\n'
            f'<p align="center">{label_picture("acknowledgements", 27)}</p>\n\n'
            + '\n\n'.join(rows) + '\n')
