"""Omarchy as the origin, routed to its creator, then linked inspiration cards in pairs."""
import hashlib
from html import escape
import json
from pathlib import Path

from folio_connections import ROUTE_INK, SIGNAL_INK
from folio_vectors import inline_svg

FOLIO = Path(__file__).resolve().parents[1] / 'folio'
ORIGIN_SLUG = 'origin-omarchy'
# 624 x 234 units is exactly 248 x 93 px. The route leaves the wordmark at the
# lower image edge and continues through the creator card's 16-unit top margin,
# so two independently linked images join without a gap.
ORIGIN_HEIGHT = 234
WORDMARK_WIDTH = 478


def config():
    return json.loads((FOLIO / 'acknowledgements.json').read_text())


def people():
    return config()['people']


def origin():
    return config()['origin']


def acknowledgement_svg(person, mode):
    avatar = json.loads((FOLIO / 'avatar-sources.json').read_text())['avatars'][person['slug']]
    assert avatar['github'].casefold() == person['github'].casefold()
    assert avatar['width'] == avatar['height']
    assert hashlib.sha256((FOLIO / avatar['path']).read_bytes()).hexdigest() == avatar['sha256']
    dark = mode == 'dark'
    paper, edge, ink, secondary = ('#191c1e', '#353a3d', '#e8e3d9', '#bfc4c9') if dark else ('#e9e7e0', '#c6c5bf', '#262522', '#50565b')
    outline = 'M24 16H600V174L578 196H24Z'
    route = (f'\n  <path d="M312 0V16" fill="none" stroke="{ROUTE_INK[mode]}" stroke-width="2.5" />'
             f'\n  <path d="M301 16H323" fill="none" stroke="{SIGNAL_INK[mode]}" stroke-width="3" />'
             if person['slug'] == origin()['creator'] else '')
    return f'''<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1248" height="448" viewBox="0 0 624 224">
  <title>{escape(person['name'])} / {escape(person['role'])}; public GitHub avatar</title>
  <defs><filter id="float" x="-15%" y="-50%" width="130%" height="210%" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="8" /><feOffset dy="10" /></filter></defs>
  <path d="{outline}" fill="#000000" opacity="{'0.48' if dark else '0.19'}" filter="url(#float)" />
  <path d="{outline}" fill="{paper}" stroke="{edge}" stroke-width="1.5" />{route}
  <image x="36" y="42" width="128" height="128" xlink:href="{escape(avatar['path'], quote=True)}" />
  <text x="392" y="96" text-anchor="middle" fill="{ink}" font-family="IBM Plex Sans" font-size="46" font-weight="600">{escape(person['name'])}</text>
  <text x="392" y="150" text-anchor="middle" fill="{secondary}" font-family="IBM Plex Sans" font-size="40" font-weight="500">{escape(person['role'])}</text>
</svg>'''


def origin_svg(mode):
    # The orange paint-only wordmark, kept vector-native until rasterization.
    height = WORDMARK_WIDTH * 950 / 4131
    start = 16 + height + 24
    wordmark = inline_svg('omarchy-wordmark-orange.svg', x=(624 - WORDMARK_WIDTH) // 2, y=16,
                          width=WORDMARK_WIDTH, height=round(height, 3))
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="1248" height="{ORIGIN_HEIGHT * 2}" viewBox="0 0 624 {ORIGIN_HEIGHT}">
  <title>{escape(origin()['name'])} — where it began, routed to its creator</title>
  {wordmark}
  <path d="M312 {start:.3f}V{ORIGIN_HEIGHT}" fill="none" stroke="{ROUTE_INK[mode]}" stroke-width="2.5" />
  <path d="M312 {start + 12:.3f}V{start + 36:.3f}" fill="none" stroke="{SIGNAL_INK[mode]}" stroke-width="3.5" />
</svg>'''


def picture(url, slug, alt, height, top=False):
    # Top alignment lets the explicit line break join the origin route exactly.
    align = ' align="top"' if top else ''
    return (f'<a href="{escape(url, quote=True)}"><picture>'
            f'<source media="(prefers-color-scheme: dark)" srcset="./assets/{slug}-dark.png" />'
            f'<img src="./assets/{slug}-light.png" width="248" height="{height}" alt="{escape(alt, quote=True)}"{align} />'
            '</picture></a>')


def acknowledgement_markdown():
    from folio_labels import label_picture
    source, everyone = origin(), people()
    creator = next(person for person in everyone if person['slug'] == source['creator'])

    def card(person, top=False):
        return picture(person['url'], f'thanks-{person["slug"]}', f'{person["name"]} / {person["role"]}', 89, top)

    head = (picture(source['url'], ORIGIN_SLUG, source['name'], round(ORIGIN_HEIGHT * 248 / 624), top=True)
            + '<br />' + card(creator, top=True))
    cards = [card(person) for person in everyone if person is not creator]
    rows = ['<p align="center">' + ''.join(cards[start:start + 2]) + '</p>'
            for start in range(0, len(cards), 2)]
    return ('<!-- Generated by scripts/build_folio.py. Omarchy routes to its creator; then two inspiration cards per row. -->\n'
            '<p><a href="https://github.com/HANCORE-linux">← Back to profile</a></p>\n\n'
            f'<p align="center">{label_picture("acknowledgements", 27)}</p>\n\n'
            f'<p align="center">{head}</p>\n\n'
            + '\n\n'.join(rows) + '\n')
