#!/usr/bin/env python3
"""Render fresh local previews through GitHub's Markdown API (or explicit offline fallback)."""
from __future__ import annotations
import argparse
import hashlib
import html
import json
import os
import re
import tempfile
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
PAGES = [
    ("README.md", "preview.html", "HANCORE — Profile"),
    ("THEMES.md", "themes.html", "HANCORE — Theme archive"),
    ("ACKNOWLEDGEMENTS.md", "acknowledgements.html", "HANCORE — Acknowledgements"),
]
CONTEXT = "HANCORE-linux/HANCORE-linux"


def source_hash(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def local_links(rendered: str) -> str:
    for source, output, _ in PAGES:
        for prefix in ("./", f"/{CONTEXT}/blob/main/"):
            rendered = rendered.replace(f'href="{prefix}{source}', f'href="./{output}')
    return rendered


def render_markdown(markdown: str, offline: bool = False) -> tuple[str, str]:
    payload = json.dumps({"text": markdown, "mode": "gfm", "context": CONTEXT}).encode()
    cache = ROOT / ".review/cache" / (hashlib.sha256(payload).hexdigest() + ".html")
    if cache.is_file():
        return local_links(cache.read_text()), "GitHub Markdown · cached"
    if offline:
        from markdown_it import MarkdownIt
        rendered = MarkdownIt("commonmark", {"html": True}).enable("table").render(markdown)
        def heading(match):
            level, body = match.groups()
            name = re.sub(r"[^\w\- ]", "", re.sub("<[^>]+>", "", body).lower()).replace(" ", "-")
            return f'<h{level} id="{html.escape(name)}">{body}</h{level}>'
        rendered = re.sub(r"<h([1-6])>(.*?)</h\1>", heading, rendered)
        return local_links(rendered), "Offline approximation · not GitHub-rendered"
    headers = {"Accept": "application/vnd.github+json", "Content-Type": "application/json",
               "User-Agent": "HANCORE-profile-preview", "X-GitHub-Api-Version": "2022-11-28"}
    if token := os.environ.get("GITHUB_TOKEN"):
        headers["Authorization"] = f"Bearer {token}"
    request = Request("https://api.github.com/markdown", data=payload, headers=headers, method="POST")
    try:
        with urlopen(request, timeout=30) as response:
            rendered = response.read().decode()
    except (HTTPError, URLError) as error:
        raise SystemExit(f"Markdown rendering failed: {error}. Use --offline for an explicitly labeled fallback.") from error
    cache.parent.mkdir(parents=True, exist_ok=True)
    cache.write_text(rendered)
    return local_links(rendered), "GitHub Markdown"


def page_html(source: str, output: str, title: str, rendered: str, renderer: str, digest: str) -> str:
    tabs = "".join(f'<a href="./{p}"' + (' aria-current="page"' if p == output else '') + f'>{label}</a>'
                   for p, label in [("preview.html", "Overview"), ("themes.html", "Themes"), ("acknowledgements.html", "Credits")])
    return f'''<!doctype html>
<!-- Generated by scripts/render_previews.py. -->
<html lang="en" data-theme="dark" data-view="profile">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="profile-source-sha256" content="{digest}">
  <title>{title}</title>
  <script src="scripts/preview/preview.js"></script>
  <link rel="stylesheet" href="scripts/preview/github-markdown.min.css">
  <link rel="stylesheet" href="scripts/preview/github-markdown-themes.css">
  <link rel="stylesheet" href="scripts/preview/preview.css">
</head>
<body>
  <a class="skip-link" href="#main-content">Skip to content</a>
  <header class="preview-toolbar">
    <div><strong>HANCORE-linux / Profilvorschau</strong><small>{renderer} · nur lokal</small></div>
    <div class="preview-controls">
      <label for="preview-view">Ansicht</label>
      <select id="preview-view"><option value="profile">Profilrahmen</option><option value="readme">Nur README</option></select>
      <label for="preview-theme">Design</label>
      <select id="preview-theme"><option value="dark">Dunkel</option><option value="light">Hell</option><option value="auto">System</option></select>
    </div>
  </header>
  <nav class="preview-tabs" aria-label="Preview pages">{tabs}</nav>
  <div class="profile-layout">
    <aside class="profile-sidebar" aria-label="Profile">
      <img class="profile-avatar" src="./assets/brand/avatar-h-construct.png" width="256" height="256" alt="HANCORE constructed H avatar">
      <strong class="profile-name">HANCORE</strong><span class="profile-handle">HANCORE-linux</span>
      <p class="profile-bio">Linux interfaces, shells &amp; themes.<br>Built for Omarchy.</p>
      <a class="profile-link" href="https://github.com/HANCORE-linux">View on GitHub</a>
    </aside>
    <main id="main-content" class="profile-frame">
      <div class="profile-label">HANCORE-linux / {source}</div>
      <article class="markdown-body" data-theme="dark">
{rendered}
      </article>
    </main>
  </div>
  <footer class="preview-footer">Lokale Designvorschau mit GitHub-Markdown. Der Profilrahmen ist angenähert; dein veröffentlichtes GitHub-Profil bleibt unverändert.</footer>
</body>
</html>
'''


def theme_css() -> str:
    original = (ROOT / "scripts/preview/github-markdown.min.css").read_text()
    blocks = re.findall(r"@media \(prefers-color-scheme:(dark|light)\)\{\.markdown-body,\[data-theme=\1\]\{([^{}]+)\}\}", original)
    if len(blocks) != 2:
        raise ValueError("Cannot extract the vendored GitHub color variables")
    return "/* Generated from the vendored stylesheet; only enables the preview theme switch. */\n" + "\n".join(
        f'.markdown-body[data-theme="{theme}"]{{{variables}}}' for theme, variables in blocks) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--offline", action="store_true")
    args = parser.parse_args()
    outputs = {"scripts/preview/github-markdown-themes.css": theme_css()}
    for source, output, title in PAGES:
        markdown = (ROOT / source).read_text()
        rendered, renderer = render_markdown(markdown, args.offline)
        outputs[output] = page_html(source, output, title, rendered, renderer, source_hash(markdown))
        print(f"{source} → {output} ({renderer})")
    outputs["index.html"] = '<!doctype html><html lang="en"><meta charset="utf-8"><title>HANCORE</title><script>location.replace("preview.html"+location.search+location.hash)</script><a href="preview.html">Open profile preview</a></html>\n'
    # Stage every page before replacing a previous preview; failed API calls leave it untouched.
    with tempfile.TemporaryDirectory(prefix="hancore-preview-") as temp:
        for i, (name, content) in enumerate(outputs.items()):
            staged = Path(temp) / str(i)
            staged.write_text(content)
            target = ROOT / name
            # Temp file on the target filesystem makes replacement atomic.
            with tempfile.NamedTemporaryFile(dir=target.parent, delete=False, prefix=".preview-") as handle:
                handle.write(staged.read_bytes())
                replacement = Path(handle.name)
            replacement.replace(target)
    inputs = [p[0] for p in PAGES] + ["scripts/render_previews.py", "scripts/preview/preview.css",
              "scripts/preview/preview.js", "scripts/preview/github-markdown.min.css"]
    manifest = {"inputs": {p: source_hash((ROOT / p).read_text()) for p in inputs},
                "outputs": {p: source_hash((ROOT / p).read_text()) for p in outputs}}
    (ROOT / ".review/preview-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


if __name__ == "__main__":
    main()
