#!/usr/bin/env python3
"""Build a separate, GitHub-rendered editorial draft without touching the old preview."""
import argparse
import hashlib
import json
import subprocess
import tempfile
from pathlib import Path

from render_previews import ROOT, page_html, render_markdown, source_hash


def signature(ink):
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 100">
  <title>HANCORE</title>
  <g transform="translate(0 13) scale(.14)" fill="{ink}">
    <path d="M80 64h104v144l24 24v48l-24 24v144H80V320l32-32v-64l-32-32V64Z"/>
    <path d="M328 64h104v128l-32 32v64l32 32v128H328V304l-24-24v-48l24-24V64Z"/>
    <path d="M184 208h144v96H184z"/>
    <path fill="#df6124" d="M220 240h72v32h-72z"/>
  </g>
  <text x="86" y="67" fill="{ink}" font-family="Nimbus Sans, Arial, sans-serif" font-size="50" font-weight="700" letter-spacing="2">HANCORE</text>
</svg>'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--offline', action='store_true')
    args = parser.parse_args()
    source = ROOT / 'concept/README.md'
    markdown = source.read_text()
    # Resolve draft-relative links for a preview page served at the repository root.
    preview_markdown = markdown.replace('"./assets/', '"./concept/assets/').replace('"../assets/', '"./assets/').replace('"../THEMES.md"', '"./THEMES.md"')
    rendered, renderer = render_markdown(preview_markdown, args.offline)
    page = page_html('concept/README.md', 'concept.html', 'HANCORE — Editorial concept', rendered, renderer, source_hash(markdown))
    page = page.replace('<!-- Generated by scripts/render_previews.py. -->', '<!-- Generated by scripts/render_concept.py. -->')
    page = page.replace('HANCORE-linux / Profilvorschau', 'HANCORE / Editorial-Entwurf')
    page = page.replace(f'{renderer} · nur lokal', f'{renderer} · oberer Profilbereich · nur lokal')
    start = page.index('  <nav class="preview-tabs"')
    end = page.index('</nav>', start) + len('</nav>')
    page = page[:start] + '''  <nav class="preview-tabs" aria-label="Concept comparison">
    <a href="./concept.html" aria-current="page">Neuer Entwurf</a>
    <a href="./preview.html">Bisheriger Stand</a>
  </nav>''' + page[end:]
    page = page.replace('</head>', '  <script src="concept/preview.js" defer></script>\n</head>')
    page = page.replace('Lokale Designvorschau mit GitHub-Markdown. Der Profilrahmen ist angenähert; dein veröffentlichtes GitHub-Profil bleibt unverändert.',
                        'Konzeptstudie für den oberen Profilbereich. Noch kein vollständiges Profil. Der bisherige Entwurf und dein veröffentlichtes GitHub-Profil bleiben unverändert.')
    outputs = ['concept.html']
    target = ROOT / 'concept/assets'
    target.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='hancore-concept-') as temp:
        for mode, ink in [('dark', '#ebe5d6'), ('light', '#242722')]:
            svg = Path(temp) / f'signature-{mode}.svg'
            png = target / f'signature-{mode}.png'
            svg.write_text(signature(ink))
            subprocess.run(['rsvg-convert', str(svg), '-o', str(png)], check=True)
            outputs.append(str(png.relative_to(ROOT)))
    (ROOT / 'concept.html').write_text(page)
    inputs = ['concept/README.md', 'concept/preview.js', 'scripts/render_concept.py', 'scripts/render_previews.py',
              'assets/themes/roseofdune.webp', 'assets/systems/shibumi.webp', 'assets/brand/avatar-h-construct.png',
              'scripts/preview/preview.css', 'scripts/preview/preview.js', 'scripts/preview/github-markdown.min.css',
              'scripts/preview/github-markdown-themes.css']
    checksum = lambda name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest()
    manifest = {'renderer': renderer, 'inputs': {p: checksum(p) for p in inputs}, 'outputs': {p: checksum(p) for p in outputs}}
    (ROOT / '.review/concept-manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(f'concept/README.md → concept.html ({renderer})')


if __name__ == '__main__':
    main()
