mode = "dark"

accent = "#e33d84"
selection = "#1d201d"
selection_background = "#1d201d"
selection_foreground = "#dee1c8"
muted = "#585d58"

hyprland_active_border = "rgba(fd5ea0b3) rgba(fd5ea0b3) rgba(89974ab3) rgba(89974ab3) rgba(89974ab3) rgba(89974ab3) rgba(89974ab3) rgba(89974ab3) 270deg"
hyprland_inactive_border = "rgba(3b403b99)"

background = "#040704"
dark_background = "#030503"
darker_background = "#020402"
lighter_background = "#1d201d"

foreground = "#D3D7B5"
dark_foreground = "#9ea188"
light_foreground = "#daddc0"
bright_foreground = "#dee1c8"

red = "#ee585d"
yellow = "#d3dd2c"
orange = "#f37276"
green = "#747f11"
cyan = "#7d7a56"
blue = "#e33d84"
magenta = "#d54a8e"
brown = "#954144"

bright_red = "#ff676a"
bright_yellow = "#d9ec04"
bright_green = "#8fa20a"
bright_cyan = "#89974a"
bright_blue = "#fd5ea0"
bright_magenta = "#fc71b8"

color0 = "#040704"
color1 = "#ee585d"
color2 = "#747f11"
color3 = "#d3dd2c"
color4 = "#e33d84"
color5 = "#d54a8e"
color6 = "#7d7a56"
color7 = "#D3D7B5"
color8 = "#585d58"
color9 = "#ff676a"
color10 = "#8fa20a"
color11 = "#d9ec04"
color12 = "#fd5ea0"
color13 = "#fc71b8"
color14 = "#89974a"
color15 = "#dee1c8"
